# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='author',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
