# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 01:30
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_text',
            field=redactor.fields.RedactorField(default='hello'),
            preserve_default=False,
        ),
    ]
