# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 19:03
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170702_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(),
        ),
    ]
