# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170702_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='post_body',
        ),
    ]
