# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_headline_text', models.CharField(max_length=250)),
                ('about_body', wagtail.wagtailcore.fields.RichTextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ('-about_headline_text',),
            },
        ),
        migrations.CreateModel(
            name='Marquee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_text', models.CharField(max_length=250)),
                ('headline_text', models.TextField(default='Sample short description')),
                ('button_text', models.CharField(max_length=50)),
                ('button_link', models.CharField(max_length=150)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ('-welcome_text',),
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_headline_text', models.CharField(max_length=250)),
                ('services_body', models.TextField(default='Sample short description')),
                ('glyph_icon', models.CharField(default='glyphicon glyphicon-heart', max_length=250)),
            ],
            options={
                'ordering': ('-services_headline_text',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('person_title', models.CharField(max_length=250)),
                ('bio', models.TextField(default='Sample short description')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('read_more_link_txt', models.CharField(default='Read More', max_length=100)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
    ]
