# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='about',
            name='release_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='marquee',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='marquee',
            name='release_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='services',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='services',
            name='release_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='team',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='release_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
