# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20170818_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marquee',
            options={'ordering': ('-release_date',)},
        ),
    ]
