# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.FileField(upload_to='')),
                ('link', models.CharField(default='Learn More', max_length=250)),
                ('link_txt', models.CharField(default='www.marketingbye.com', max_length=100)),
                ('release_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
    ]
