# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='link',
            field=models.CharField(default='www.marketingbye.com', max_length=250),
        ),
        migrations.AlterField(
            model_name='partner',
            name='link_txt',
            field=models.CharField(default='Learn More', max_length=100),
        ),
    ]
