# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20171112_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('section_number', models.PositiveIntegerField(blank=True, unique=True)),
                ('release_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
    ]
