# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_title_color_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='color_class',
            field=models.CharField(choices=[('blackTxt', 'blackTxt'), ('whiteTxt', 'whiteTxt')], default='blackTxt', max_length=8),
        ),
    ]
